# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Config1t.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Config1t(object):
    def setupUi(self, Config1t):
        Config1t.setObjectName("Config1t")
        Config1t.resize(534, 607)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        Config1t.setFont(font)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Config1t)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tconfig_frm_cfg = QtWidgets.QFrame(Config1t)
        self.tconfig_frm_cfg.setEnabled(True)
        self.tconfig_frm_cfg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tconfig_frm_cfg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tconfig_frm_cfg.setObjectName("tconfig_frm_cfg")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tconfig_frm_cfg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_warn0 = QtWidgets.QLabel(self.tconfig_frm_cfg)
        self.lbl_warn0.setTextFormat(QtCore.Qt.RichText)
        self.lbl_warn0.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_warn0.setObjectName("lbl_warn0")
        self.verticalLayout.addWidget(self.lbl_warn0)
        self.lbl_warn0_2 = QtWidgets.QLabel(self.tconfig_frm_cfg)
        self.lbl_warn0_2.setTextFormat(QtCore.Qt.RichText)
        self.lbl_warn0_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_warn0_2.setObjectName("lbl_warn0_2")
        self.verticalLayout.addWidget(self.lbl_warn0_2)
        self.label = QtWidgets.QLabel(self.tconfig_frm_cfg)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.grid_cfgword = QtWidgets.QGridLayout()
        self.grid_cfgword.setObjectName("grid_cfgword")
        self.form_col0 = QtWidgets.QFormLayout()
        self.form_col0.setObjectName("form_col0")
        self.lbl_flashwe = QtWidgets.QLabel(self.tconfig_frm_cfg)
        self.lbl_flashwe.setObjectName("lbl_flashwe")
        self.form_col0.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_flashwe)
        self.chbox_flashwe = QtWidgets.QCheckBox(self.tconfig_frm_cfg)
        self.chbox_flashwe.setText("")
        self.chbox_flashwe.setChecked(True)
        self.chbox_flashwe.setObjectName("chbox_flashwe")
        self.form_col0.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.chbox_flashwe)
        self.lbl_jtagen = QtWidgets.QLabel(self.tconfig_frm_cfg)
        self.lbl_jtagen.setObjectName("lbl_jtagen")
        self.form_col0.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_jtagen)
        self.chbox_jtagen = QtWidgets.QCheckBox(self.tconfig_frm_cfg)
        self.chbox_jtagen.setText("")
        self.chbox_jtagen.setChecked(True)
        self.chbox_jtagen.setObjectName("chbox_jtagen")
        self.form_col0.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.chbox_jtagen)
        self.grid_cfgword.addLayout(self.form_col0, 0, 0, 1, 1)
        self.form_col1 = QtWidgets.QFormLayout()
        self.form_col1.setObjectName("form_col1")
        self.lbl_nvrwe = QtWidgets.QLabel(self.tconfig_frm_cfg)
        self.lbl_nvrwe.setObjectName("lbl_nvrwe")
        self.form_col1.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_nvrwe)
        self.grid_cfgword.addLayout(self.form_col1, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.grid_cfgword)
        self.verticalLayout_2.addWidget(self.tconfig_frm_cfg)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)

        self.retranslateUi(Config1t)
        QtCore.QMetaObject.connectSlotsByName(Config1t)

    def retranslateUi(self, Config1t):
        _translate = QtCore.QCoreApplication.translate
        Config1t.setWindowTitle(_translate("Config1t", "Form"))
        self.lbl_warn0.setText(_translate("Config1t", "<html><head/><body><p><span style=\" color:#ef2929;\">Изменяйте состояние конфигурации с осторожностью!</span></p></body></html>"))
        self.lbl_warn0_2.setText(_translate("Config1t", "<html><head/><body><p><span style=\" color:#ef2929;\">Изменения вступят в силу только после сброса контроллера!</span></p></body></html>"))
        self.label.setText(_translate("Config1t", "CFGWORD"))
        self.lbl_flashwe.setToolTip(_translate("Config1t", "<html><head/><body><p align=\"justify\">0 - запрещение записи и стирания основной области Flash-памяти</p><p align=\"justify\">1 - разрешение записи и стирания основной области Flash-памяти</p></body></html>"))
        self.lbl_flashwe.setText(_translate("Config1t", "FLASHWE"))
        self.lbl_jtagen.setToolTip(_translate("Config1t", "<html><head/><body><p>0 - запрещение работы JTAG/SWD функции пина</p><p align=\"justify\">1 - разрешение работы JTAG/SWD функции пина</p></body></html>"))
        self.lbl_jtagen.setText(_translate("Config1t", "JTAGEN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Config1t = QtWidgets.QWidget()
    ui = Ui_Config1t()
    ui.setupUi(Config1t)
    Config1t.show()
    sys.exit(app.exec_())
