# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'memory.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Memory(object):
    def setupUi(self, Memory):
        Memory.setObjectName("Memory")
        Memory.resize(671, 517)
        self.verticalLayout = QtWidgets.QVBoxLayout(Memory)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(Memory)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 649, 459))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.table_memory = MemoryTable(self.scrollAreaWidgetContents)
        self.table_memory.setObjectName("table_memory")
        self.table_memory.setColumnCount(0)
        self.table_memory.setRowCount(0)
        self.horizontalLayout_4.addWidget(self.table_memory)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.jump_address_ledit = QtWidgets.QLineEdit(Memory)
        self.jump_address_ledit.setObjectName("jump_address_ledit")
        self.horizontalLayout_3.addWidget(self.jump_address_ledit)
        self.jump_address_btn = QtWidgets.QPushButton(Memory)
        self.jump_address_btn.setObjectName("jump_address_btn")
        self.horizontalLayout_3.addWidget(self.jump_address_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Memory)
        self.jump_address_btn.clicked.connect(self.table_memory.add_row) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Memory)

    def retranslateUi(self, Memory):
        _translate = QtCore.QCoreApplication.translate
        Memory.setWindowTitle(_translate("Memory", "Form"))
        self.jump_address_btn.setText(_translate("Memory", "PushButton"))
from view.widgets.memorytable import MemoryTable


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Memory = QtWidgets.QWidget()
    ui = Ui_Memory()
    ui.setupUi(Memory)
    Memory.show()
    sys.exit(app.exec_())
