# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 600)
        MainWindow.setMinimumSize(QtCore.QSize(500, 600))
        MainWindow.setMaximumSize(QtCore.QSize(500, 600))
        MainWindow.setWindowTitle("K1921VKx Flasher")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/flasher.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.hbox_global_opt = QtWidgets.QHBoxLayout()
        self.hbox_global_opt.setObjectName("hbox_global_opt")
        self.frm_connect = QtWidgets.QFrame(self.centralwidget)
        self.frm_connect.setMaximumSize(QtCore.QSize(16777215, 71))
        self.frm_connect.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_connect.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_connect.setObjectName("frm_connect")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frm_connect)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.hbox_port = QtWidgets.QHBoxLayout()
        self.hbox_port.setObjectName("hbox_port")
        self.combo_port = QtWidgets.QComboBox(self.frm_connect)
        self.combo_port.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.combo_port.setObjectName("combo_port")
        self.hbox_port.addWidget(self.combo_port)
        self.combo_baud = QtWidgets.QComboBox(self.frm_connect)
        self.combo_baud.setMaximumSize(QtCore.QSize(70, 16777215))
        self.combo_baud.setObjectName("combo_baud")
        self.combo_baud.addItem("")
        self.combo_baud.setItemText(0, "9600")
        self.combo_baud.addItem("")
        self.combo_baud.setItemText(1, "19200")
        self.combo_baud.addItem("")
        self.combo_baud.setItemText(2, "38400")
        self.combo_baud.addItem("")
        self.combo_baud.setItemText(3, "57600")
        self.combo_baud.addItem("")
        self.combo_baud.setItemText(4, "115200")
        self.combo_baud.addItem("")
        self.combo_baud.setItemText(5, "230400")
        self.combo_baud.addItem("")
        self.combo_baud.setItemText(6, "460800")
        self.combo_baud.addItem("")
        self.combo_baud.setItemText(7, "921600")
        self.hbox_port.addWidget(self.combo_baud)
        self.verticalLayout_11.addLayout(self.hbox_port)
        self.hbox_connect = QtWidgets.QHBoxLayout()
        self.hbox_connect.setObjectName("hbox_connect")
        self.btn_connect = QtWidgets.QPushButton(self.frm_connect)
        self.btn_connect.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_connect.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_connect.setText("Подключиться")
        self.btn_connect.setObjectName("btn_connect")
        self.hbox_connect.addWidget(self.btn_connect)
        self.verticalLayout_11.addLayout(self.hbox_connect)
        self.hbox_global_opt.addWidget(self.frm_connect)
        self.frm_flash = QtWidgets.QFrame(self.centralwidget)
        self.frm_flash.setEnabled(False)
        self.frm_flash.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_flash.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_flash.setObjectName("frm_flash")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frm_flash)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hbox_flash_select = QtWidgets.QHBoxLayout()
        self.hbox_flash_select.setObjectName("hbox_flash_select")
        self.rbtn_flash0 = QtWidgets.QRadioButton(self.frm_flash)
        self.rbtn_flash0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rbtn_flash0.setAutoFillBackground(False)
        self.rbtn_flash0.setText("FLASH0")
        self.rbtn_flash0.setChecked(True)
        self.rbtn_flash0.setObjectName("rbtn_flash0")
        self.hbox_flash_select.addWidget(self.rbtn_flash0)
        self.rbtn_flash1 = QtWidgets.QRadioButton(self.frm_flash)
        self.rbtn_flash1.setText("FLASH1")
        self.rbtn_flash1.setObjectName("rbtn_flash1")
        self.hbox_flash_select.addWidget(self.rbtn_flash1)
        self.verticalLayout.addLayout(self.hbox_flash_select)
        self.chbox_nvr = QtWidgets.QCheckBox(self.frm_flash)
        self.chbox_nvr.setText("NVR / Info область")
        self.chbox_nvr.setObjectName("chbox_nvr")
        self.verticalLayout.addWidget(self.chbox_nvr)
        self.hbox_global_opt.addWidget(self.frm_flash)
        self.verticalLayout_10.addLayout(self.hbox_global_opt)
        self.tabs_cmd = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs_cmd.setEnabled(True)
        self.tabs_cmd.setMinimumSize(QtCore.QSize(0, 349))
        self.tabs_cmd.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabs_cmd.setObjectName("tabs_cmd")
        self.tab_info = QtWidgets.QWidget()
        self.tab_info.setEnabled(False)
        self.tab_info.setObjectName("tab_info")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_info)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tinfo_hbox_info = QtWidgets.QHBoxLayout()
        self.tinfo_hbox_info.setObjectName("tinfo_hbox_info")
        self.tinfo_hbox_info_values = QtWidgets.QFormLayout()
        self.tinfo_hbox_info_values.setObjectName("tinfo_hbox_info_values")
        self.tinfo_lab_chipid = QtWidgets.QLabel(self.tab_info)
        self.tinfo_lab_chipid.setText("CHIPID")
        self.tinfo_lab_chipid.setObjectName("tinfo_lab_chipid")
        self.tinfo_hbox_info_values.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.tinfo_lab_chipid)
        self.tinfo_ledit_chipid = QtWidgets.QLineEdit(self.tab_info)
        self.tinfo_ledit_chipid.setMinimumSize(QtCore.QSize(90, 0))
        self.tinfo_ledit_chipid.setMaximumSize(QtCore.QSize(90, 16777215))
        self.tinfo_ledit_chipid.setText("0xFFFFFFFF")
        self.tinfo_ledit_chipid.setReadOnly(True)
        self.tinfo_ledit_chipid.setObjectName("tinfo_ledit_chipid")
        self.tinfo_hbox_info_values.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tinfo_ledit_chipid)
        self.tinfo_lab_cpuid = QtWidgets.QLabel(self.tab_info)
        self.tinfo_lab_cpuid.setText("CPUID")
        self.tinfo_lab_cpuid.setObjectName("tinfo_lab_cpuid")
        self.tinfo_hbox_info_values.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.tinfo_lab_cpuid)
        self.tinfo_ledit_cpuid = QtWidgets.QLineEdit(self.tab_info)
        self.tinfo_ledit_cpuid.setMinimumSize(QtCore.QSize(90, 0))
        self.tinfo_ledit_cpuid.setMaximumSize(QtCore.QSize(90, 16777215))
        self.tinfo_ledit_cpuid.setText("0xFFFFFFFF")
        self.tinfo_ledit_cpuid.setReadOnly(True)
        self.tinfo_ledit_cpuid.setObjectName("tinfo_ledit_cpuid")
        self.tinfo_hbox_info_values.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tinfo_ledit_cpuid)
        self.tinfo_lab_bootver = QtWidgets.QLabel(self.tab_info)
        self.tinfo_lab_bootver.setText("Версия загрузчика")
        self.tinfo_lab_bootver.setObjectName("tinfo_lab_bootver")
        self.tinfo_hbox_info_values.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.tinfo_lab_bootver)
        self.tinfo_ledit_bootver = QtWidgets.QLineEdit(self.tab_info)
        self.tinfo_ledit_bootver.setMinimumSize(QtCore.QSize(90, 0))
        self.tinfo_ledit_bootver.setMaximumSize(QtCore.QSize(90, 16777215))
        self.tinfo_ledit_bootver.setText("0.0")
        self.tinfo_ledit_bootver.setReadOnly(True)
        self.tinfo_ledit_bootver.setObjectName("tinfo_ledit_bootver")
        self.tinfo_hbox_info_values.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tinfo_ledit_bootver)
        self.tinfo_hbox_info.addLayout(self.tinfo_hbox_info_values)
        self.tinfo_lab_mcu = QtWidgets.QLabel(self.tab_info)
        self.tinfo_lab_mcu.setMinimumSize(QtCore.QSize(150, 0))
        self.tinfo_lab_mcu.setText("К1921ВКххх")
        self.tinfo_lab_mcu.setObjectName("tinfo_lab_mcu")
        self.tinfo_hbox_info.addWidget(self.tinfo_lab_mcu)
        self.verticalLayout_5.addLayout(self.tinfo_hbox_info)
        self.tinfo_tbl_flash = QtWidgets.QTableWidget(self.tab_info)
        self.tinfo_tbl_flash.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tinfo_tbl_flash.setShowGrid(True)
        self.tinfo_tbl_flash.setCornerButtonEnabled(False)
        self.tinfo_tbl_flash.setObjectName("tinfo_tbl_flash")
        self.tinfo_tbl_flash.setColumnCount(5)
        self.tinfo_tbl_flash.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Номер")
        self.tinfo_tbl_flash.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Адрес")
        self.tinfo_tbl_flash.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Размер")
        self.tinfo_tbl_flash.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Ч")
        self.tinfo_tbl_flash.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("З")
        self.tinfo_tbl_flash.setHorizontalHeaderItem(4, item)
        self.tinfo_tbl_flash.horizontalHeader().setVisible(True)
        self.tinfo_tbl_flash.horizontalHeader().setCascadingSectionResizes(False)
        self.tinfo_tbl_flash.horizontalHeader().setDefaultSectionSize(84)
        self.tinfo_tbl_flash.horizontalHeader().setStretchLastSection(False)
        self.tinfo_tbl_flash.verticalHeader().setVisible(False)
        self.tinfo_tbl_flash.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_5.addWidget(self.tinfo_tbl_flash)
        self.tabs_cmd.addTab(self.tab_info, "Информация")
        self.tab_write = QtWidgets.QWidget()
        self.tab_write.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_write.sizePolicy().hasHeightForWidth())
        self.tab_write.setSizePolicy(sizePolicy)
        self.tab_write.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tab_write.setObjectName("tab_write")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_write)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.twrite_frm_file = QtWidgets.QFrame(self.tab_write)
        self.twrite_frm_file.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.twrite_frm_file.setFrameShadow(QtWidgets.QFrame.Raised)
        self.twrite_frm_file.setObjectName("twrite_frm_file")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.twrite_frm_file)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.twrite_lab_fileopen = QtWidgets.QLabel(self.twrite_frm_file)
        self.twrite_lab_fileopen.setText("Выбор файла для записи (*.bin):")
        self.twrite_lab_fileopen.setObjectName("twrite_lab_fileopen")
        self.verticalLayout_3.addWidget(self.twrite_lab_fileopen)
        self.twrite_hbox_file = QtWidgets.QHBoxLayout()
        self.twrite_hbox_file.setObjectName("twrite_hbox_file")
        self.twrite_ledit_filepath = QtWidgets.QLineEdit(self.twrite_frm_file)
        self.twrite_ledit_filepath.setReadOnly(False)
        self.twrite_ledit_filepath.setObjectName("twrite_ledit_filepath")
        self.twrite_hbox_file.addWidget(self.twrite_ledit_filepath)
        self.twrite_btn_fileopen = QtWidgets.QPushButton(self.twrite_frm_file)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.twrite_btn_fileopen.sizePolicy().hasHeightForWidth())
        self.twrite_btn_fileopen.setSizePolicy(sizePolicy)
        self.twrite_btn_fileopen.setMaximumSize(QtCore.QSize(20, 16777215))
        self.twrite_btn_fileopen.setText("...")
        self.twrite_btn_fileopen.setObjectName("twrite_btn_fileopen")
        self.twrite_hbox_file.addWidget(self.twrite_btn_fileopen)
        self.verticalLayout_3.addLayout(self.twrite_hbox_file)
        self.twrite_form_addr = QtWidgets.QFormLayout()
        self.twrite_form_addr.setObjectName("twrite_form_addr")
        self.twrite_lab_addr = QtWidgets.QLabel(self.twrite_frm_file)
        self.twrite_lab_addr.setText("Адрес начала")
        self.twrite_lab_addr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.twrite_lab_addr.setObjectName("twrite_lab_addr")
        self.twrite_form_addr.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.twrite_lab_addr)
        self.twrite_ledit_addr = QtWidgets.QLineEdit(self.twrite_frm_file)
        self.twrite_ledit_addr.setMinimumSize(QtCore.QSize(90, 0))
        self.twrite_ledit_addr.setMaximumSize(QtCore.QSize(90, 16777215))
        self.twrite_ledit_addr.setText("0x00000000")
        self.twrite_ledit_addr.setObjectName("twrite_ledit_addr")
        self.twrite_form_addr.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.twrite_ledit_addr)
        self.verticalLayout_3.addLayout(self.twrite_form_addr)
        self.verticalLayout_7.addWidget(self.twrite_frm_file)
        self.twrite_frm_erase = QtWidgets.QFrame(self.tab_write)
        self.twrite_frm_erase.setMaximumSize(QtCore.QSize(16777215, 40))
        self.twrite_frm_erase.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.twrite_frm_erase.setFrameShadow(QtWidgets.QFrame.Raised)
        self.twrite_frm_erase.setObjectName("twrite_frm_erase")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.twrite_frm_erase)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.twrite_rbtn_ernone = QtWidgets.QRadioButton(self.twrite_frm_erase)
        self.twrite_rbtn_ernone.setText("Не стирать")
        self.twrite_rbtn_ernone.setObjectName("twrite_rbtn_ernone")
        self.horizontalLayout_6.addWidget(self.twrite_rbtn_ernone)
        self.twrite_rbtn_erall = QtWidgets.QRadioButton(self.twrite_frm_erase)
        self.twrite_rbtn_erall.setText("Стереть всё")
        self.twrite_rbtn_erall.setObjectName("twrite_rbtn_erall")
        self.horizontalLayout_6.addWidget(self.twrite_rbtn_erall)
        self.twrite_rbtn_erpages = QtWidgets.QRadioButton(self.twrite_frm_erase)
        self.twrite_rbtn_erpages.setText("Стереть необходимое")
        self.twrite_rbtn_erpages.setChecked(True)
        self.twrite_rbtn_erpages.setObjectName("twrite_rbtn_erpages")
        self.horizontalLayout_6.addWidget(self.twrite_rbtn_erpages)
        self.verticalLayout_7.addWidget(self.twrite_frm_erase)
        self.twrite_frm_opts = QtWidgets.QFrame(self.tab_write)
        self.twrite_frm_opts.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.twrite_frm_opts.setFrameShadow(QtWidgets.QFrame.Raised)
        self.twrite_frm_opts.setObjectName("twrite_frm_opts")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.twrite_frm_opts)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.twrite_chbox_verif = QtWidgets.QCheckBox(self.twrite_frm_opts)
        self.twrite_chbox_verif.setText("Верификация")
        self.twrite_chbox_verif.setObjectName("twrite_chbox_verif")
        self.verticalLayout_4.addWidget(self.twrite_chbox_verif)
        self.twrite_chbox_go = QtWidgets.QCheckBox(self.twrite_frm_opts)
        self.twrite_chbox_go.setText("Переход к исполнению загруженного кода")
        self.twrite_chbox_go.setObjectName("twrite_chbox_go")
        self.verticalLayout_4.addWidget(self.twrite_chbox_go)
        self.verticalLayout_7.addWidget(self.twrite_frm_opts)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.tabs_cmd.addTab(self.tab_write, "Запись")
        self.tab_erase = QtWidgets.QWidget()
        self.tab_erase.setEnabled(False)
        self.tab_erase.setObjectName("tab_erase")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_erase)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.terase_frm_erase = QtWidgets.QFrame(self.tab_erase)
        self.terase_frm_erase.setMaximumSize(QtCore.QSize(16777215, 40))
        self.terase_frm_erase.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.terase_frm_erase.setFrameShadow(QtWidgets.QFrame.Raised)
        self.terase_frm_erase.setObjectName("terase_frm_erase")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.terase_frm_erase)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.terase_rbtn_erall = QtWidgets.QRadioButton(self.terase_frm_erase)
        self.terase_rbtn_erall.setText("Стереть всё")
        self.terase_rbtn_erall.setChecked(True)
        self.terase_rbtn_erall.setObjectName("terase_rbtn_erall")
        self.horizontalLayout_7.addWidget(self.terase_rbtn_erall)
        self.terase_rbtn_erpages = QtWidgets.QRadioButton(self.terase_frm_erase)
        self.terase_rbtn_erpages.setText("Стереть страницы")
        self.terase_rbtn_erpages.setObjectName("terase_rbtn_erpages")
        self.horizontalLayout_7.addWidget(self.terase_rbtn_erpages)
        self.verticalLayout_6.addWidget(self.terase_frm_erase)
        self.terase_frm_addr = QtWidgets.QFrame(self.tab_erase)
        self.terase_frm_addr.setEnabled(False)
        self.terase_frm_addr.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.terase_frm_addr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.terase_frm_addr.setObjectName("terase_frm_addr")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.terase_frm_addr)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.terase_form_pages = QtWidgets.QFormLayout()
        self.terase_form_pages.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.terase_form_pages.setObjectName("terase_form_pages")
        self.terase_lab_firstpage = QtWidgets.QLabel(self.terase_frm_addr)
        self.terase_lab_firstpage.setText("Первая страница")
        self.terase_lab_firstpage.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.terase_lab_firstpage.setObjectName("terase_lab_firstpage")
        self.terase_form_pages.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.terase_lab_firstpage)
        self.terase_ledit_firstpage = QtWidgets.QLineEdit(self.terase_frm_addr)
        self.terase_ledit_firstpage.setMaximumSize(QtCore.QSize(50, 16777215))
        self.terase_ledit_firstpage.setText("0")
        self.terase_ledit_firstpage.setObjectName("terase_ledit_firstpage")
        self.terase_form_pages.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.terase_ledit_firstpage)
        self.terase_lab_lastpage = QtWidgets.QLabel(self.terase_frm_addr)
        self.terase_lab_lastpage.setText("Последняя страница")
        self.terase_lab_lastpage.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.terase_lab_lastpage.setObjectName("terase_lab_lastpage")
        self.terase_form_pages.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.terase_lab_lastpage)
        self.terase_ledit_lastpage = QtWidgets.QLineEdit(self.terase_frm_addr)
        self.terase_ledit_lastpage.setMaximumSize(QtCore.QSize(50, 16777215))
        self.terase_ledit_lastpage.setText("0")
        self.terase_ledit_lastpage.setObjectName("terase_ledit_lastpage")
        self.terase_form_pages.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.terase_ledit_lastpage)
        self.horizontalLayout.addLayout(self.terase_form_pages)
        self.terase_lab_or = QtWidgets.QLabel(self.terase_frm_addr)
        self.terase_lab_or.setText("или")
        self.terase_lab_or.setObjectName("terase_lab_or")
        self.horizontalLayout.addWidget(self.terase_lab_or)
        self.terase_form_addr = QtWidgets.QFormLayout()
        self.terase_form_addr.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.terase_form_addr.setObjectName("terase_form_addr")
        self.terase_lab_bytes = QtWidgets.QLabel(self.terase_frm_addr)
        self.terase_lab_bytes.setText("Количество байт")
        self.terase_lab_bytes.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.terase_lab_bytes.setObjectName("terase_lab_bytes")
        self.terase_form_addr.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.terase_lab_bytes)
        self.terase_ledit_bytes = QtWidgets.QLineEdit(self.terase_frm_addr)
        self.terase_ledit_bytes.setMinimumSize(QtCore.QSize(90, 0))
        self.terase_ledit_bytes.setMaximumSize(QtCore.QSize(90, 16777215))
        self.terase_ledit_bytes.setText("0")
        self.terase_ledit_bytes.setObjectName("terase_ledit_bytes")
        self.terase_form_addr.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.terase_ledit_bytes)
        self.terase_lab_addrstart = QtWidgets.QLabel(self.terase_frm_addr)
        self.terase_lab_addrstart.setText("Адрес начала")
        self.terase_lab_addrstart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.terase_lab_addrstart.setObjectName("terase_lab_addrstart")
        self.terase_form_addr.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.terase_lab_addrstart)
        self.terase_ledit_addrstart = QtWidgets.QLineEdit(self.terase_frm_addr)
        self.terase_ledit_addrstart.setMinimumSize(QtCore.QSize(90, 0))
        self.terase_ledit_addrstart.setMaximumSize(QtCore.QSize(90, 16777215))
        self.terase_ledit_addrstart.setText("0x00000000")
        self.terase_ledit_addrstart.setObjectName("terase_ledit_addrstart")
        self.terase_form_addr.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.terase_ledit_addrstart)
        self.horizontalLayout.addLayout(self.terase_form_addr)
        self.verticalLayout_6.addWidget(self.terase_frm_addr)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.tabs_cmd.addTab(self.tab_erase, "Стирание")
        self.tab_read = QtWidgets.QWidget()
        self.tab_read.setEnabled(False)
        self.tab_read.setObjectName("tab_read")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_read)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tread_frm_file = QtWidgets.QFrame(self.tab_read)
        self.tread_frm_file.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tread_frm_file.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tread_frm_file.setObjectName("tread_frm_file")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tread_frm_file)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tread_lab_fileopen = QtWidgets.QLabel(self.tread_frm_file)
        self.tread_lab_fileopen.setText("Выбор файла для сохранения (*.bin):")
        self.tread_lab_fileopen.setObjectName("tread_lab_fileopen")
        self.verticalLayout_8.addWidget(self.tread_lab_fileopen)
        self.tread_hbox_file = QtWidgets.QHBoxLayout()
        self.tread_hbox_file.setObjectName("tread_hbox_file")
        self.tread_ledit_filepath = QtWidgets.QLineEdit(self.tread_frm_file)
        self.tread_ledit_filepath.setReadOnly(False)
        self.tread_ledit_filepath.setObjectName("tread_ledit_filepath")
        self.tread_hbox_file.addWidget(self.tread_ledit_filepath)
        self.tread_btn_fileopen = QtWidgets.QPushButton(self.tread_frm_file)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tread_btn_fileopen.sizePolicy().hasHeightForWidth())
        self.tread_btn_fileopen.setSizePolicy(sizePolicy)
        self.tread_btn_fileopen.setMaximumSize(QtCore.QSize(20, 16777215))
        self.tread_btn_fileopen.setText("...")
        self.tread_btn_fileopen.setObjectName("tread_btn_fileopen")
        self.tread_hbox_file.addWidget(self.tread_btn_fileopen)
        self.verticalLayout_8.addLayout(self.tread_hbox_file)
        self.tread_hbox_addr = QtWidgets.QHBoxLayout()
        self.tread_hbox_addr.setObjectName("tread_hbox_addr")
        self.tread_form_pages = QtWidgets.QFormLayout()
        self.tread_form_pages.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tread_form_pages.setObjectName("tread_form_pages")
        self.tread_lab_firstpage = QtWidgets.QLabel(self.tread_frm_file)
        self.tread_lab_firstpage.setText("Первая страница")
        self.tread_lab_firstpage.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tread_lab_firstpage.setObjectName("tread_lab_firstpage")
        self.tread_form_pages.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.tread_lab_firstpage)
        self.tread_ledit_firstpage = QtWidgets.QLineEdit(self.tread_frm_file)
        self.tread_ledit_firstpage.setMaximumSize(QtCore.QSize(50, 16777215))
        self.tread_ledit_firstpage.setText("0")
        self.tread_ledit_firstpage.setObjectName("tread_ledit_firstpage")
        self.tread_form_pages.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tread_ledit_firstpage)
        self.tread_lab_lastpage = QtWidgets.QLabel(self.tread_frm_file)
        self.tread_lab_lastpage.setText("Последняя страница")
        self.tread_lab_lastpage.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tread_lab_lastpage.setObjectName("tread_lab_lastpage")
        self.tread_form_pages.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.tread_lab_lastpage)
        self.tread_ledit_lastpage = QtWidgets.QLineEdit(self.tread_frm_file)
        self.tread_ledit_lastpage.setMaximumSize(QtCore.QSize(50, 16777215))
        self.tread_ledit_lastpage.setText("0")
        self.tread_ledit_lastpage.setObjectName("tread_ledit_lastpage")
        self.tread_form_pages.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tread_ledit_lastpage)
        self.tread_hbox_addr.addLayout(self.tread_form_pages)
        self.tread_lab_or = QtWidgets.QLabel(self.tread_frm_file)
        self.tread_lab_or.setText("или")
        self.tread_lab_or.setObjectName("tread_lab_or")
        self.tread_hbox_addr.addWidget(self.tread_lab_or)
        self.tread_form_addr = QtWidgets.QFormLayout()
        self.tread_form_addr.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tread_form_addr.setObjectName("tread_form_addr")
        self.tread_lab_addrstart = QtWidgets.QLabel(self.tread_frm_file)
        self.tread_lab_addrstart.setText("Адрес начала")
        self.tread_lab_addrstart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tread_lab_addrstart.setObjectName("tread_lab_addrstart")
        self.tread_form_addr.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.tread_lab_addrstart)
        self.tread_ledit_addrstart = QtWidgets.QLineEdit(self.tread_frm_file)
        self.tread_ledit_addrstart.setMinimumSize(QtCore.QSize(90, 0))
        self.tread_ledit_addrstart.setMaximumSize(QtCore.QSize(90, 16777215))
        self.tread_ledit_addrstart.setText("0x00000000")
        self.tread_ledit_addrstart.setObjectName("tread_ledit_addrstart")
        self.tread_form_addr.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tread_ledit_addrstart)
        self.tread_lab_bytes = QtWidgets.QLabel(self.tread_frm_file)
        self.tread_lab_bytes.setText("Количество байт")
        self.tread_lab_bytes.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tread_lab_bytes.setObjectName("tread_lab_bytes")
        self.tread_form_addr.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.tread_lab_bytes)
        self.tread_ledit_bytes = QtWidgets.QLineEdit(self.tread_frm_file)
        self.tread_ledit_bytes.setMinimumSize(QtCore.QSize(90, 0))
        self.tread_ledit_bytes.setMaximumSize(QtCore.QSize(90, 16777215))
        self.tread_ledit_bytes.setText("0")
        self.tread_ledit_bytes.setObjectName("tread_ledit_bytes")
        self.tread_form_addr.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tread_ledit_bytes)
        self.tread_hbox_addr.addLayout(self.tread_form_addr)
        self.verticalLayout_8.addLayout(self.tread_hbox_addr)
        self.verticalLayout_2.addWidget(self.tread_frm_file)
        self.tread_frm_verif = QtWidgets.QFrame(self.tab_read)
        self.tread_frm_verif.setMaximumSize(QtCore.QSize(16777215, 100))
        self.tread_frm_verif.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tread_frm_verif.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tread_frm_verif.setObjectName("tread_frm_verif")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tread_frm_verif)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tread_chbox_verif = QtWidgets.QCheckBox(self.tread_frm_verif)
        self.tread_chbox_verif.setText("Верификация")
        self.tread_chbox_verif.setObjectName("tread_chbox_verif")
        self.verticalLayout_9.addWidget(self.tread_chbox_verif)
        self.tread_lab_verif_fileopen = QtWidgets.QLabel(self.tread_frm_verif)
        self.tread_lab_verif_fileopen.setText("Выбор файла для верификации (*.bin):")
        self.tread_lab_verif_fileopen.setObjectName("tread_lab_verif_fileopen")
        self.verticalLayout_9.addWidget(self.tread_lab_verif_fileopen)
        self.tread_hbox_verif_file = QtWidgets.QHBoxLayout()
        self.tread_hbox_verif_file.setObjectName("tread_hbox_verif_file")
        self.tread_ledit_verif_filepath = QtWidgets.QLineEdit(self.tread_frm_verif)
        self.tread_ledit_verif_filepath.setReadOnly(False)
        self.tread_ledit_verif_filepath.setObjectName("tread_ledit_verif_filepath")
        self.tread_hbox_verif_file.addWidget(self.tread_ledit_verif_filepath)
        self.tread_btn_verif_fileopen = QtWidgets.QPushButton(self.tread_frm_verif)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tread_btn_verif_fileopen.sizePolicy().hasHeightForWidth())
        self.tread_btn_verif_fileopen.setSizePolicy(sizePolicy)
        self.tread_btn_verif_fileopen.setMaximumSize(QtCore.QSize(20, 16777215))
        self.tread_btn_verif_fileopen.setText("...")
        self.tread_btn_verif_fileopen.setObjectName("tread_btn_verif_fileopen")
        self.tread_hbox_verif_file.addWidget(self.tread_btn_verif_fileopen)
        self.verticalLayout_9.addLayout(self.tread_hbox_verif_file)
        self.verticalLayout_2.addWidget(self.tread_frm_verif)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.tabs_cmd.addTab(self.tab_read, "Чтение")
        self.tab_config = QtWidgets.QWidget()
        self.tab_config.setEnabled(False)
        self.tab_config.setObjectName("tab_config")
        self.tconf_lab_test = QtWidgets.QLabel(self.tab_config)
        self.tconf_lab_test.setGeometry(QtCore.QRect(9, 9, 57, 16))
        self.tconf_lab_test.setObjectName("tconf_lab_test")
        self.tabs_cmd.addTab(self.tab_config, "Конфигурация")
        self.verticalLayout_10.addWidget(self.tabs_cmd)
        self.btn_exec = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exec.setEnabled(False)
        self.btn_exec.setText("Выполнить")
        self.btn_exec.setObjectName("btn_exec")
        self.verticalLayout_10.addWidget(self.btn_exec)
        self.tedit_log = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.tedit_log.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Fixed")
        self.tedit_log.setFont(font)
        self.tedit_log.setObjectName("tedit_log")
        self.verticalLayout_10.addWidget(self.tedit_log)
        self.pbar_cmd = QtWidgets.QProgressBar(self.centralwidget)
        self.pbar_cmd.setProperty("value", 0)
        self.pbar_cmd.setTextVisible(True)
        self.pbar_cmd.setInvertedAppearance(False)
        self.pbar_cmd.setObjectName("pbar_cmd")
        self.verticalLayout_10.addWidget(self.pbar_cmd)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 500, 20))
        self.menuBar.setObjectName("menuBar")
        self.menu_file = QtWidgets.QMenu(self.menuBar)
        self.menu_file.setTitle("Файл")
        self.menu_file.setObjectName("menu_file")
        self.menu_help = QtWidgets.QMenu(self.menuBar)
        self.menu_help.setTitle("Помощь")
        self.menu_help.setObjectName("menu_help")
        MainWindow.setMenuBar(self.menuBar)
        self.act_exit = QtWidgets.QAction(MainWindow)
        self.act_exit.setText("Выход")
        self.act_exit.setShortcut("Ctrl+Q")
        self.act_exit.setObjectName("act_exit")
        self.act_about = QtWidgets.QAction(MainWindow)
        self.act_about.setText("О программе")
        self.act_about.setObjectName("act_about")
        self.menu_file.addAction(self.act_exit)
        self.menu_help.addAction(self.act_about)
        self.menuBar.addAction(self.menu_file.menuAction())
        self.menuBar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        self.combo_baud.setCurrentIndex(4)
        self.tabs_cmd.setCurrentIndex(0)
        self.act_exit.triggered.connect(MainWindow.close)
        self.act_about.triggered.connect(MainWindow.handle_act_about_triggered)
        self.btn_connect.clicked.connect(MainWindow.handle_btn_connect_clicked)
        self.rbtn_flash0.toggled['bool'].connect(MainWindow.handle_flash_select_toggled)
        self.rbtn_flash1.toggled['bool'].connect(MainWindow.handle_flash_select_toggled)
        self.chbox_nvr.toggled['bool'].connect(MainWindow.handle_chbox_nvr_toggled)
        self.btn_exec.clicked.connect(MainWindow.handle_btn_exec_clicked)
        self.twrite_ledit_filepath.editingFinished.connect(MainWindow.handle_twrite_ledit_filepath_editint_finished)
        self.twrite_ledit_addr.editingFinished.connect(MainWindow.handle_twrite_ledit_addr_editing_finished)
        self.twrite_btn_fileopen.clicked.connect(MainWindow.handle_twrite_btn_fileopen_clicked)
        self.terase_ledit_firstpage.editingFinished.connect(MainWindow.handle_terase_ledit_firstpage_editing_finished)
        self.terase_ledit_lastpage.editingFinished.connect(MainWindow.handle_terase_ledit_lastpage_editing_finished)
        self.terase_ledit_addrstart.editingFinished.connect(MainWindow.handle_terase_ledit_addrstart_editing_finished)
        self.terase_ledit_bytes.editingFinished.connect(MainWindow.handle_terase_ledit_bytes_editing_finished)
        self.tread_ledit_filepath.editingFinished.connect(MainWindow.handle_tread_ledit_filepath_editing_finished)
        self.tread_btn_fileopen.clicked.connect(MainWindow.handle_tread_btn_fileopen_clicked)
        self.tread_ledit_firstpage.editingFinished.connect(MainWindow.handle_tread_ledit_firstpage_editing_finished)
        self.tread_ledit_lastpage.editingFinished.connect(MainWindow.handle_tread_ledit_lastpage_editing_finished)
        self.tread_ledit_addrstart.editingFinished.connect(MainWindow.handle_tread_ledit_addrstart_editing_finished)
        self.tread_ledit_bytes.editingFinished.connect(MainWindow.handle_tread_ledit_bytes_editing_finished)
        self.tread_chbox_verif.toggled['bool'].connect(MainWindow.handle_tread_chbox_verif_toggled)
        self.tread_ledit_verif_filepath.editingFinished.connect(MainWindow.handle_tread_ledit_verif_filepath_editing_finished)
        self.tread_btn_verif_fileopen.clicked.connect(MainWindow.handle_tread_btn_verif_fileopen_clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.tconf_lab_test.setText(_translate("MainWindow", "TextLabel"))

import ui_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

